### ISSUE TITLE
rename project

### ISSUE THREAD

**Issue by amilajack** [tide-app/tide#60]
- Rename all references of "freesound player" to "tide" in the source
- rename the project

### Tasks
- [ ] Buy domain name
- [ ] Rename github project
- [ ] Rename all references to "freesound-player"
